In [7]:
import numpy as np
import random
from random import random



Scalar

In [24]:
#create
scalar=random() 
#read
print(scalar)
#update
scalar= 12.3
print(scalar)
#delate
del scalar
print("The scalar was deleted")

0.28007326004067146
12.3
The scalar was deleted


Vector

In [30]:
#create
v = np.arange(1,20,2)
#read
print("The vector is\n",v)
#update
v = np.append(v, 27)
print("Updated vector - ",v)
#delate
v = np.delete(v, len(v)-1)
print("Delete lust number\n",v)
del v
print("The vector was deleted")

The vector is
 [ 1  3  5  7  9 11 13 15 17 19]
Updated vector -  [ 1  3  5  7  9 11 13 15 17 19 27]
Delete lust number
 [ 1  3  5  7  9 11 13 15 17 19]
The vector was deleted


Matrix

In [36]:
#create
A = np.matrix('1 7 3; 4 9 6')
#read
print("The matrix:\n",A)
#update
A_new = A*2
print("New matrix:\n",A_new)
#delate
del A_new
print("The matrix was deleted")




The matrix:
 [[1 7 3]
 [4 9 6]]
New matrix:
 [[ 2 14  6]
 [ 8 18 12]]
The matrix was deleted
